import StarsCanvas from '@/components/main/StarBackground'
import './globals.css'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import Navbar from '@/components/main/Navbar'
import Footer from '@/components/main/Footer'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'NET TRIX - CYBERSECURITY',
  description: 'Generated by Net-trix',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={'$(inter.className) bg-[#030014]  overflow-x-hidden'}>
        <StarsCanvas />
        <Navbar/>
        {children}
        <Footer/>
        </body>
    </html>
  )
}
